version: '3.3'

services:
  web:
    build: .
    restart: unless-stopped
    command: python3 /backend/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 8080:8000
