# Generated by Django 3.1.14 on 2022-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(default=0)),
                ('pid', models.PositiveIntegerField(default=0)),
                ('start_time', models.CharField(default='', max_length=30)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('client_location', models.CharField(default='', max_length=255)),
                ('client_postal_code', models.CharField(default='', max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('start_time', models.CharField(default='', max_length=30)),
                ('end_time', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('author_id', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('daySelector', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=100)),
                ('about', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('photoid', models.CharField(default='', max_length=200)),
                ('photoid_verified', models.CharField(default='', max_length=30)),
                ('certificate', models.CharField(default='', max_length=200)),
                ('certificate_verified', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
