# Generated by Django 3.1.14 on 2022-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
