# Generated by Django 3.1.14 on 2022-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
