# Generated by Django 3.1.14 on 2022-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.TextField(default=''),
        ),
    ]
