# Generated by Django 3.1.14 on 2022-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('start_time', models.CharField(default='', max_length=30)),
                ('end_time', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('author_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
