# Generated by Django 3.1.14 on 2022-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='daySelector',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
