# Generated by Django 3.1.14 on 2022-07-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(default=0)),
                ('pid', models.PositiveIntegerField(default=0)),
                ('start_time', models.CharField(default='', max_length=30)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
